#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

mv system/fvSchemes_steady system/fvSchemes

# Cycle #1 - AOA 00
cp system/controlDict_AOA_steady/controlDict_aoa00 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa00 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA00

mv postProcessing aero_aoa00

./Allclean


# Cycle #2 - AOA 01
cp system/controlDict_AOA_steady/controlDict_aoa01 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa01 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA01

mv postProcessing aero_aoa01

./Allclean


# Cycle #3 - AOA 02
cp system/controlDict_AOA_steady/controlDict_aoa02 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa02 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA02

mv postProcessing aero_aoa02

./Allclean


# Cycle #4 - AOA 03
cp system/controlDict_AOA_steady/controlDict_aoa03 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa03 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA03

mv postProcessing aero_aoa03

./Allclean


# Cycle #5 - AOA 04
cp system/controlDict_AOA_steady/controlDict_aoa04 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa04 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA04

mv postProcessing aero_aoa04

./Allclean


# Cycle #6 - AOA 05
cp system/controlDict_AOA_steady/controlDict_aoa05 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa05 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA05

mv postProcessing aero_aoa05

./Allclean


# Cycle #7 - AOA 06
cp system/controlDict_AOA_steady/controlDict_aoa06 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa06 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA06

mv postProcessing aero_aoa06

./Allclean


# Cycle #8 - AOA 07
cp system/controlDict_AOA_steady/controlDict_aoa07 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa07 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA07

mv postProcessing aero_aoa07

./Allclean


# Cycle #9 - AOA 08
cp system/controlDict_AOA_steady/controlDict_aoa08 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa08 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA08

mv postProcessing aero_aoa08

./Allclean


# Cycle #10 - AOA 09
cp system/controlDict_AOA_steady/controlDict_aoa09 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa09 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA09

mv postProcessing aero_aoa09

./Allclean


# Cycle #11 - AOA 10
cp system/controlDict_AOA_steady/controlDict_aoa10 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa10 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA10

mv postProcessing aero_aoa10

./Allclean


# Cycle #12 - AOA 11
cp system/controlDict_AOA_steady/controlDict_aoa11 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa11 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA11

mv postProcessing aero_aoa11

./Allclean


# Cycle #13 - AOA 12
cp system/controlDict_AOA_steady/controlDict_aoa12 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa12 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA12

mv postProcessing aero_aoa12

./Allclean


# Cycle #14 - AOA 13
cp system/controlDict_AOA_steady/controlDict_aoa13 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa13 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA13

mv postProcessing aero_aoa13

./Allclean


# Cycle #15 - AOA 14
cp system/controlDict_AOA_steady/controlDict_aoa14 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa14 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA14

mv postProcessing aero_aoa14

./Allclean


# Cycle #16 - AOA 15
cp system/controlDict_AOA_steady/controlDict_aoa15 system/controlDict

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

cp 0/U15_AOA/U_aoa15 0/U

runApplication massBoussinesqSimpleFoam

foamToVTK

mv VTK VTK_AOA15

mv postProcessing aero_aoa15

#./Allclean

# ----------------------------------------------------------------- end-of-file
