#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication extrudeMesh
runApplication createPatch -overwrite

cp -r 0.org 0

runApplication massBoussinesqSimpleFoam

#runApplication rhoPimpleFoam

# ----------------------------------------------------------------- end-of-file
