#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Clean time directories only
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd snappyHex
cleanCase


##-- Clean case 260K --##
cd ../260K
cleanCase
rm -rf 0

# ----------------------------------------------------------------- end-of-file
