#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd snappyHex
runApplication blockMesh
runApplication snappyHexMesh -overwrite


##-- Run case 260K --##
cd ../260K
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.orig 0

runApplication massBoussinesqSimpleFoam

# ----------------------------------------------------------------- end-of-file
