#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


##--Run case 260K--##
cd 260K
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0

runApplication massBoussinesqSimpleFoam


##--Run case 262K--##
cd ../262K
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0

runApplication massBoussinesqSimpleFoam


##--Run case 264K--##
cd ../264K
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0

runApplication massBoussinesqSimpleFoam


##--Run case 266K--##
cd ../266K
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0

runApplication massBoussinesqSimpleFoam


##--Run case 268K--##
cd ../268K
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0

runApplication massBoussinesqSimpleFoam


##--Run case 270K--##
cd ../270K
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0

runApplication massBoussinesqSimpleFoam


##-- Return to directory --##
cd ../

# ----------------------------------------------------------------- end-of-file
