#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Clean time directories only
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


##-- Clean case 260K --##
cd 260K
cleanCase
rm -rf 0


##-- Clean case 262K --##
cd ../262K
cleanCase
rm -rf 0


##-- Clean case 264K --##
cd ../264K
cleanCase
rm -rf 0


##-- Clean case 266K --##
cd ../266K
cleanCase
rm -rf 0


##-- Clean case 268K --##
cd ../268K
cleanCase
rm -rf 0


##-- Clean case 270K --##
cd ../270K
cleanCase
rm -rf 0

##-- Return to directory --##
cd ../

# ----------------------------------------------------------------- end-of-file
