#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


##-- Run snappyHexMesh --##
cd snappyHex
runApplication blockMesh
runApplication snappyHexMesh -overwrite


##-- Return to directory --##
cd ../

# ----------------------------------------------------------------- end-of-file
