#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Clean time directories only

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd ../simpleFoam
cleanCase
rm -rf 0

# ----------------------------------------------------------------- end-of-file
